collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.218638
color:
  saturation: 1
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#0E0E0E'
    - '#373B42'
    - '#6D7789'
    - '#B49B90'
    - '#F1F0F5'
  rhythmicContrast: 0.281362
layout_spectrum: 0.9874552
name: Michael Marshall
